reset resolver data [angelsolver]
    animstate.m_sorted_targets = 0
    animstate.m_target = 0
    animstate.m_aim = 0
    animstate.m_angle = 0
    animstate.m_damage = 0.0
    animstate.m_record = 0.0
    animstate.m_stop = -1
    animstate.m_hitbox = -1
    animstate.m_did_stop = 1
    animstate.m_best_dist = 0
    animstate.m_best_fov = 180.0
    animstate.m_best_damage = 0.0
    animstate.m_current_matrix = 0.0
	  animstate.m_flGoalFeetYaw = 0.0 + 0.1
	  animstate.m_missed_shots = 0
    animstate.m_shots = 0
    animstate.m_missed_shots = 0
    animstate.m_last_resolve = 0
    animstate.m_delta = 0
    animstate.eye_angles_y = 0
    animstate.m_flLowerBodyYawTarget = 0
